cleaned code Solution add fixed bug with EventToGo
EventsExpress-SoftServe/EventsExpress pull request #116
Opened 2020-10-19 12:18 UTC by ArdeaSt

Close #112  and Close #114

2020-10-19 13:09 UTC, iuriikhrystiuk requested changes

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/IServices/ICountryService.cs
> +        // Country GetByName(string name);
Remove commented code, please.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/CategoryService.cs
> +        private readonly IUnitOfWork db;
Please start the private field with underscore.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/CityService.cs
> +        private readonly IUnitOfWork db;
Same as above.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/CommentService.cs
> +        public IUnitOfWork Db { get; set; }
Does it really need to be public? Probably make it a private field.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/Custom.ruleset
> +﻿<?xml version="1.0" encoding="utf-8"?>
Remove this file please.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/RoleService.cs
> +        public IUnitOfWork Db { get; set; }
Also make it a private field.

2020-10-19 13:09 UTC, iuriikhrystiuk commented on EventsExpress.Db/Repo/UnitOfWork.cs
> +        private readonly AppDbContext database;
Start field with underscore.

2020-10-19 19:04 UTC, ArdeaSt commented on EventsExpress.Db/Repo/UnitOfWork.cs
> +        private readonly AppDbContext database;
Did it

2020-10-19 19:05 UTC, ArdeaSt commented on EventsExpress.Core/Services/RoleService.cs
> +        public IUnitOfWork Db { get; set; }
It can be private, remaked)

2020-10-19 19:05 UTC, ArdeaSt commented on EventsExpress.Core/Services/Custom.ruleset
> +﻿<?xml version="1.0" encoding="utf-8"?>
removed

2020-10-19 19:11 UTC, ArdeaSt commented on EventsExpress.Core/Services/CommentService.cs
> +        public IUnitOfWork Db { get; set; }
In this case, we can use private field.

2020-10-19 19:11 UTC, ArdeaSt commented on EventsExpress.Core/Services/CityService.cs
> +        private readonly IUnitOfWork db;
did it

2020-10-19 19:12 UTC, ArdeaSt commented on EventsExpress.Core/Services/CategoryService.cs
> +        private readonly IUnitOfWork db;
changed name of field

2020-10-19 19:12 UTC, ArdeaSt commented on EventsExpress.Core/IServices/ICountryService.cs
> +        // Country GetByName(string name);
removed

2020-10-20 09:32 UTC, iuriikhrystiuk approved these changes

2020-10-20 09:37 UTC, merged