Fix uncorrect loading of some pages
EventsExpress-SoftServe/EventsExpress pull request #145
Opened 2020-10-30 15:19 UTC by Anastasiagumenuk9

Close #143

2020-10-30 21:13 UTC, sand0 requested changes
You shouldn't call ToList() on each step of query building. This causing loading all the data from db. Call smth like `events = events.ToLis()` before mapping call

2020-11-02 07:51 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventService.cs
> +
Remove the extra whitespaces please.

2020-11-02 14:36 UTC, iuriikhrystiuk approved these changes

2020-11-02 18:52 UTC, sand0 approved these changes

2020-11-02 18:53 UTC, merged