#123 aviability to create recurrent event
EventsExpress-SoftServe/EventsExpress pull request #201
Opened 2020-11-23 20:24 UTC by Anastasiagumenuk9

Close #123

2020-11-23 20:38 UTC, sand0 requested changes

2020-11-23 20:38 UTC, sand0 commented on EventsExpress/ClientApp/src/components/event/event-leave-modal.js
> +        debugger;
remove this from PR

2020-11-23 20:38 UTC, sand0 commented on EventsExpress/ClientApp/src/store/initialState.js
> +        userSearchFilter: null
looks like this is created by error

2020-11-24 07:33 UTC, iuriikhrystiuk commented on EventsExpress.Db/Migrations/20201123180134_AddeventScheduleTable.cs
> +                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));
Don't do the default constraints.

2020-11-24 09:30 UTC, closed without merging