Implement multiply owners for events
EventsExpress-SoftServe/EventsExpress pull request #225
Opened 2020-11-26 14:13 UTC by S4ress

Close #125

2020-11-26 15:06 UTC, iuriikhrystiuk requested changes

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/DTOs/EventDTO.cs
> +        public IEnumerable<Guid> OwnerId { get; set; }
Please name it `OwnerIds`.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Notifications/BlockedEventMessage.cs
> +        public IEnumerable<Guid> UserId { get; }
Again, proper naming for collection of objects, please.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventService.cs
> +        private UserDTO CurrentUser { get; set; }
Please, don't store a private field. This can get replaced in the middle of execution for different threads. If you want to share the calls, consider doing it per method. Remove this property.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventService.cs
> +            var data = events.ToList();
Don't do `Tolist` call here. It will materialize the whole db list. Please remove this line.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventStatusHistoryService.cs
> +            // record.UserId = e.OwnerId;
Remove commented code please. And get user from `HttpContext`.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/UserService.cs
> +            var ownEventsIds = Db.EventOwnersRepository.Get()
I think for ratings we should get not owners, but visitors. @sand0 ?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Db/EF/AppDbContext.cs
>              // user-event configs
Remove redundant comments please.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Db/Entities/EventSchedule.cs
> +
Please remove redundant enter.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Db/Entities/ManageableEntity.cs
> +        public void ModifyBy(Guid UserId)
Don't add methods to entities. If you want to make it centralized - consider implementing it inside AppDbContext.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Db/EventsExpress.Db.csproj
> +  <ItemGroup>
Undo this itemgroup please.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Db/Migrations/20201107090613_AddMultiplyEventOwners.cs
> +                name: "UserId",
Why do we need a `UserId` column in `Event` table?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/actions/event-item-view.js
> +        if (response.error == null) {
Do we need these extra whitespaces?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/actions/event-item-view.js
> +        const res1 = api_serv.getEvent(eventId);
Please, don't name it `res1`. Use a logical name e.g.: `eventResult`, etc.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/app/app.js
> -                        <Route path="/admin/events" component={EventsForAdmin} />
Why did we remove this navigation?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/event-item-view.js
> +			inventories
Why the huge offset?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/event-item-view.js
> +        //let isPending = !isMyEvent && visitorsEnum.pendingUsers.find(x => x.id === current_user.id) != null;
Why commentig the `pending`?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/event-item.js
> +        var owner = owners.find(x => x);
Where do we use this `owner`?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/simple-modal.js
> +            IsOpen: false,
Please name properties using cameCase instead of PascalCase.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/services/EventsExpressService.js
> +    OnDeleteFromOwners = async (data) => {
Again, camalCase naming please.

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/Controllers/EventScheduleController.cs
> -            if (!ModelState.IsValid)
Why removed the validation?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/DTO/UserPreviewDto.cs
> +using Microsoft.AspNetCore.Http;
Do we need the extra using?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress/Mapping/EventScheduleAutoMapper.cs
> -                .ForMember(dest => dest.Event, opts => opts.MapFrom(src => new EventDTO
Why was this mapping removed?

2020-11-26 15:06 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventService.cs
> +        public async Task<OperationResult> PromoteToOwner(Guid userId, Guid eventId)
Let's extract these methods to separate service. This service is overloaded with responsibility.

2020-11-27 07:32 UTC, sand0 commented on EventsExpress.Core/Services/UserService.cs
> +            var ownEventsIds = Db.EventOwnersRepository.Get()
@iuriikhrystiuk , we have two different rating calculations. The first one for the event: rate = Avg(Sum(all rates from visitors to this event)).
And the other one is for the user (here): rate = Avg(Sum(all rates from visitors to all events owned by this user)).

So as we change to the multiple owners model, looks like there is the correct solution here - find all events where owners contain the user.

2020-11-27 07:41 UTC, sand0 commented on EventsExpress/ClientApp/src/components/app/app.js
> -                        <Route path="/admin/events" component={EventsForAdmin} />
I've proposed to do this 'cause the "EventsForAdmin" (by route admin/events) component is the bugged copy of "Events"( home/events) and it does not contain any different logic.
So probably we have to remove the full "EventsForAdmin" chain or change his responsibility

2020-11-27 12:57 UTC, S4ress commented on EventsExpress/Mapping/EventScheduleAutoMapper.cs
> -                .ForMember(dest => dest.Event, opts => opts.MapFrom(src => new EventDTO
it is not used anywhere

2020-11-27 18:19 UTC, iuriikhrystiuk requested changes

2020-11-27 18:19 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventStatusHistoryService.cs
> -            record.UserId = e.OwnerId;
Please, apply `userId` from `HttpContext` here.

2020-11-27 18:19 UTC, iuriikhrystiuk commented on EventsExpress.Db/Migrations/20201107090613_AddMultiplyEventOwners.cs
> +            migrationBuilder.CreateIndex(
Did you regenerate migrations or removed the column reference? Please, regenerate migrations - there should not be such column.

2020-11-27 18:19 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/simple-modal.js
> +            Id: null,
This has to be named using camelCase as well. Please do that.

2020-12-01 16:07 UTC, iuriikhrystiuk commented on EventsExpress.Db/EF/AppDbContext.cs
> +            Database.SetCommandTimeout(60);
Remove these lines from constructor.

2020-12-01 16:07 UTC, iuriikhrystiuk commented on EventsExpress.Db/EF/AppDbContext.cs
> +
Do we need these extra lines here?

2020-12-01 16:07 UTC, iuriikhrystiuk commented on EventsExpress.Test/ServiceTests/EventServiceTest.cs
> +<<<<<<< HEAD
You have not finished merging here. Did you run the application?

2020-12-02 06:12 UTC, iuriikhrystiuk approved these changes, later dismissed

2020-12-02 13:59 UTC, iuriikhrystiuk approved these changes

2020-12-02 14:20 UTC, merged