Fixed: avability to create duplicate of an existing category
EventsExpress-SoftServe/EventsExpress pull request #341
Opened 2020-12-16 11:39 UTC by Anastasiagumenuk9

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

An admin can create duplicate of an existing category (if non-printable spaces are used)

## Summary of change

- Implemented TrimModelBinder to trim strings from view models
- Edited method for displaying errors
- Move actions for category to a separate folder
- Move reducers for category to a separate folder

## Testing approach

ToDo

## CHECK LIST
- [ ]  Сode coverage >=___%
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2020-12-16 12:27 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/services/CategoryService.js
> +            Name: data.Name
Consider using `camelCaseNameResolver` when binding.

2020-12-16 12:27 UTC, iuriikhrystiuk commented on EventsExpress/Startup.cs
> +                options.AllowSynchronousIO = true;
Why is this required?

2020-12-16 15:35 UTC, sand0 requested changes

2020-12-16 15:35 UTC, sand0 commented on EventsExpress/EventsExpress.csproj
> +    <PackageReference Include="Microsoft.AspNet.Mvc" Version="5.2.7" />
Is this required?

2020-12-16 15:35 UTC, sand0 commented on EventsExpress.Core/Services/CategoryService.cs
> +            if (ExistsByName(title))
This logic has been added to the validation layer, so can be removed from here

2020-12-16 15:35 UTC, sand0 commented on EventsExpress.Core/Services/CategoryService.cs
> +            if (ExistsByName(category.Name))
This logic has been added to the validation layer, so can be removed from here

2020-12-16 15:43 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/services/CategoryService.js
> +        const res = await baseService.setResource('category/delete/${data}');
Are we sure we need to change string interpolation into standard string?

2020-12-16 15:43 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/services/CategoryService.js
> +            name: data.Name
Please consider also changing the naming to camelcase where it is coming from.

2020-12-17 14:18 UTC, sand0 approved these changes

2020-12-17 14:23 UTC, merged