Implement draft
EventsExpress-SoftServe/EventsExpress pull request #442
Opened 2021-02-24 13:16 UTC by farmgun

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-03-03 13:54 UTC, farmgun commented
/AzurePipelines run eventsexpress

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress.Core/Services/EventService.cs
> +                    // check db (null fields)
This comment does not make any sense. Remove it please.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/actions/event-list-action.js
> +export function get_drafts() {
Please rework this method to use handle errors using refactored functionality.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/edit-event-new.js
> +class EditEventNew extends Component {
Please, do not name components '-new'. Rename it to show functionality appropriately.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/event-item-view.js
> +                                <EventDraftWrapper
Why is here event draft if it is simple event? Are you sure it is correct?

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/containers/event-draft-list.js
> +        const queryString = eventHelper.getQueryStringByEventFilter(this.props.events.filter);
There is no filtering for drafts. Remove this code please.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/containers/event-item-draft-view.js
> +                <EventListWrapper location={this.props.location} />
Why is EventListWraper rendered for EventItemDraftWrapper? Are they reused?

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/containers/event-item-view-new.js
> +class EventItemViewWrapperNew extends Component{
Rename component appropriately to show what it is doing, not '-new'.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress/EventsExpress.csproj
> +  <ItemGroup>
Undo this file.

2021-03-03 14:44 UTC, iuriikhrystiuk commented on EventsExpress.Core/Exceptions/EventsExpressException.cs
> +        public Dictionary<string, string> CustomData { get; set; }
Please name it not so broadely. Consider 'ValidationErrors'.

2021-03-10 13:25 UTC, iuriikhrystiuk commented on EventsExpress.Core/IServices/IEventService.cs
> +        IEnumerable<EventDto> GetAllDraftEvents(int page, int pageSize, Guid user_id, out int count);
Why do you need to pass in the user id? It can be accessed using `IHttpContextAccessor`.

2021-03-10 13:25 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/app/app.js
> +                        <Route path='/Drafts/:page' component={EventDraftListWrapper} />
This route does not have to have parameter `:page` if you are not storing the page there. Please remove it.

2021-03-10 13:25 UTC, iuriikhrystiuk commented on EventsExpress/ClientApp/src/components/event/event-item-view-new.js
> +﻿
Remove this file altogether.

2021-03-11 13:30 UTC, iuriikhrystiuk submitted a review, later dismissed

2021-03-24 10:46 UTC, sand0 requested changes
@farmgun, one more staff you should have done for this PR:
please, just drop both existing migrations and regenerate the single new one

2021-03-24 13:15 UTC, sand0 approved these changes

2021-03-24 13:17 UTC, merged