Fix Notifications #513
EventsExpress-SoftServe/EventsExpress pull request #572
Opened 2021-05-04 16:46 UTC by stannydan

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-07 06:56 UTC, sand0 requested changes

2021-05-07 06:56 UTC, sand0 commented on EventsExpress.Core/Services/EventService.cs
> +                await _mediator.Publish(new EventCreatedMessage(dtos));
Let add a unit test to verify this method was invoked to avoid the same issue in the future

2021-05-12 11:59 UTC, iuriikhrystiuk submitted a review, later dismissed

2021-05-12 12:01 UTC, sand0 approved these changes, later dismissed

2021-05-12 12:12 UTC, sand0 approved these changes

2021-05-12 12:20 UTC, merged