Add secret.json
EventsExpress-SoftServe/EventsExpress pull request #585
Opened 2021-05-14 09:59 UTC by stannydan

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-05-17 06:34 UTC, iuriikhrystiuk commented
What about key vault providers? Are they automatically included?

2021-05-17 06:34 UTC, iuriikhrystiuk reviewed
What about key vault providers? Are they automatically included?

2021-05-17 19:13 UTC, sand0 requested changes

2021-05-17 19:13 UTC, sand0 commented on EventsExpress/appsettings.json
> +    "JwtEmailEncryption": "YOUR JWT EMAIL ENCRYPTION"
I guess this one is useless, so can be deleted

2021-05-19 10:00 UTC, iuriikhrystiuk submitted a review, later dismissed

2021-05-19 13:13 UTC, sand0 approved these changes

2021-05-19 15:46 UTC, merged