789 Fix email confirmation
EventsExpress-SoftServe/EventsExpress pull request #872
Opened 2021-10-08 10:50 UTC by InnaShapovalova

dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

2021-10-08 11:24 UTC, iuriikhrystiuk approved these changes, later dismissed

2021-10-08 13:37 UTC, sand0 requested changes, later dismissed

2021-10-08 13:37 UTC, sand0 commented on EventsExpress/appsettings.Development.json
> +  "AppBaseUrl": {
revert this file

2021-10-15 11:17 UTC, iuriikhrystiuk approved these changes

2021-10-15 11:37 UTC, merged